### ISSUE TITLE
Dupe bug w/ Cooking for Blockheads

### ISSUE THREAD

**Issue by purpleposeidon** [gigaherz/Survivalist#43] opened 2017-04-24 20:58 UTC
This is the mod that does the "`Your [Stone Shovel] broke but you got 1x[Stick] in return`", right?

Putting a tool (eg, a shovel) in a cooking for blockheads toolrack does the "your tool broke", giving sticks/etc, but the tool doesn't actually break. This can be repeated at maximum speed by just holding down right click. (The toolrack works with any tool, not just Cooking For Blockheads tool.)

**Comment by gigaherz** [comment] 2017-04-24 21:03
I'll take a look, but I'm not sure that this is something I can fix.

**Comment by purpleposeidon** [comment] 2017-04-24 21:09
PlayerDestroyItemEvent?

**Comment by gigaherz** [comment] 2017-04-24 21:46
That is exactly what I'm using.

**Comment by gigaherz** [comment] 2017-04-24 21:47
It fires any time a stack becomes 0, even if it's like, a stack of dirt you are placing.

**Comment by gigaherz** [comment] 2017-04-24 21:48
For reference: https://github.com/gigaherz/Survivalist/blob/master/src/main/java/gigaherz/survivalist/scraping/ItemBreakingTracker.java#L241

**Comment by purpleposeidon** [comment] 2017-04-25 00:45
Hmm, and CookingForBlockheads doesn't even seem to use that event, so they're prooobably not calling it inappropriately? I've pinged them.

**Comment by blay09** [comment] 2017-04-25 11:11
I'm unable to reproduce the issue using Cooking for Blockheads 5.3.20 and Survivalist 1.9.0.

**Comment by gigaherz** [comment] 2017-04-25 11:18
@purpleposeidon What exact versions are you using? And, are there other mods installed?

**Comment by purpleposeidon** [comment] 2017-04-25 20:51
Ack! Sorry, I should've mentioned 1.10. The bug still occurs with only `Survivalist-1.10.2-1.9.0.jar` and `CookingForBlockheads_1.10.2-4.2.39.jar` on forge 1.10.2-12.18.3.2281.

**Comment by gigaherz** [comment] 2017-04-26 15:49
I just had a chance to drop CFBh into my 1.10.2 development environment, and the issue does indeed happen.(for reference, it requires using a tool that has been enchanted with Scraping).

However, I don't think that I can fix it, because the event is sent just by the fact that the stack in the hand is empty after the item use. There's absolutely no information about the reason. So besides messing with the game's bytecode -- which I'm not willing to do --, I don't see any way to do this correctly. You may need to disable the feature unless CFBh can do something to prevent it from their end.

**Comment by blay09** [comment] 2017-04-26 16:32
Issue should be fixed in the [newest Cooking for Blockheads](http://jenkins.blay09.net/job/Cooking%20for%20Blockheads%201.10/lastSuccessfulBuild/) version.

**Comment by gigaherz** [comment] 2017-04-26 16:35
Nice! Closing this, then. :)

**Closed by gigaherz** 2017-04-26 16:35 UTC
